// Solution:


fn main() {
    // fix the error
    let _arr = [1, 2, 3];
    println!("Success!");
}


/* 
Explantion/What I understood:

changed '3' -> 3 and it fixes the errors.

*/