// Solution:


fn main() {
    for n in 1..100 {
        if n == 100 {
            panic!("NEVER LET THIS RUN")
        }
    }
} 


/* 
Explantion/What I understood:

1..=100 -> 1..100 and it solves the error.


*/